spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    username: root
    url: jdbc:mysql://localhost:3306/javaweb_wcf?serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql

  freemarker:
    suffix: .ftl